* [33maf2ebb3[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mrefactor[m[33m, [m[1;31morigin/webchat[m[33m, [m[1;32mwebchat[m[33m)[m Enhance GET chat messages endpoint to include Instagram field for each message by fetching user data from the User model.
* [33md379ae6[m Add Instagram field to user registration response and new user creation logic
* [33m8c2d069[m Enhance user profile management by adding Instagram URL validation and updating the profile update logic. Modify the profile page to include Instagram input and display, and update the Chat component to show Instagram links in messages. Extend User model and AuthContext to support Instagram field.
* [33m2709cf2[m Refactor Chat component to use a Map for message storage, ensuring uniqueness by _id. Update message handling logic for receiving, deleting, and editing messages. Adjust rendering logic to accommodate the new data structure and improve performance.
* [33m042414f[m Remove MongoDB setup documentation from MONGODB_SETUP.md, streamlining project files and focusing on essential components.
* [33me29f97d[m Update Chat component to connect to external WebSocket server for real-time chat functionality, replacing the local development URL.
* [33mf2a67c5[m Enhance chat component with improved message handling and user experience; add scroll button for new messages, suppress error logs in HLS proxy, and update service worker to log cache errors. Remove Socket.IO server code and connect to external server for real-time chat functionality.
* [33m86dd43d[m Add socket.io and socket.io-client dependencies; update service worker for new wave icons and improve error handling in cache operations. Refactor page components for better user experience and integrate user session management in AuthContext.
* [33m408acea[m[33m ([m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)[m Refactor hospedaje page to improve iframe error handling and loading states; replace iframe with image preview for Leidymar Apartments. Update manifest.json by removing redundant image entries for better clarity.
* [33m245479b[m Enhance AdminPage with user editing and deletion functionality; integrate EditUserModal for improved user management. Update login route to validate email format and enhance error handling in registration. Refactor SurfCam and AuthContext to manage user session timers and improve user experience for free tier users.
* [33m7e7660b[m Update README.md to include new premium password variable and adjust formatting. Refactor SimpleHeader component to remove unnecessary login button. Modify AuthContext to utilize environment variable for premium access control, enhancing security and flexibility in password management.
* [33mae301d8[m Update README.md to reflect new branding as "Santa Teresa Surf Cam" and enhance feature descriptions. Add details about PWA capabilities, MongoDB integration, and user analytics. Revise installation instructions and environment variables for MongoDB Atlas. Include new admin panel features and contact information for support.
* [33m53b02fc[m Update dependencies in package.json and package-lock.json; add bcryptjs and mongoose packages, and upgrade @radix-ui/react-tabs to version 1.1.13. Modify manifest.json for icon updates and enhance layout.tsx with viewport settings. Refactor hospedaje page to include a new header and add a premium plan CTA. Improve PWA installation experience in InstallPWAButton and SurfCam components with user instructions. Update AuthContext for better user session management and error handling.
* [33m898af84[m Implement installation state management in Login and SurfCam components; add loading indicators during app installation and improve user feedback for installation status.
* [33m9a49716[m Refactor AppHeader, Login, and SurfCam components to improve mobile responsiveness and user experience; implement guest and premium login modes in Login, enhance navigation in AppHeader, and streamline PWA installation prompts in SurfCam.
* [33m86ffdd9[m Enhance PWA installation experience by adding debug information and user prompts; update InstallPWAButton and SurfCam components to manage installation state and provide manual installation instructions when necessary.
* [33m37bc5d2[m Update PWA configuration and layout to include new wave icon; enhance caching in service worker and manifest for improved performance and visual consistency.
* [33m10a62f5[m Enhance HlsPlayer to manage HLS instance globally and improve pause functionality; update SurfCam to handle fullscreen exit and video playback upon trial expiration, including user notifications and redirection.
* [33mbae33b0[m Update app layout and components to reflect new branding as "Santa Teresa Surf Cam"; enhance PWA support with manifest and meta tags; refactor headers and login component for consistency.
* [33m5a70ea2[m Refactor ContactoPage to use SimpleHeader; enhance HlsPlayer for improved autoplay handling and error management; update Login component to include a link to premium plans; modify SurfCam to allow user-driven navigation after trial expiration.
